### ISSUE TITLE
syntax error near unexpected token `)'

### ISSUE THREAD

**Issue by slice-mani** [bhowell2/github-substring-action#1]
It's is giving some syntax error as below
```
Run echo =0 --tags)
  echo =0 --tags)
  shell: /usr/bin/bash -e {0}
  env:
    GH_TOKEN: 
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64
/home/runner/work/_temp/68ea493b-4550-4707-8a36-3b49d401a466.sh: line 1: syntax error near unexpected token `)'
Error: Process completed with exit code 2.
```
Here is my action
```
      - name: substring-action
        uses: bhowell2/github-substring-action@v1.0.0
        id: get_version
        with:
          value: $(git describe --abbrev=0 --tags)
          index_of_str: "v"
```
What is the problem?

**Comment by bhowell2** [comment]
@slice-mani sorry, didnt see this (only 6 months later...). Did you figure it out? Been a while since i've touched any github actions, but seems like it tried to run a subshell here and failed or something? I'm not even sure of the syntax at the moment. Lemme know if you figured it out or if it's still a problem. Looks like I need to update this a bit anyway.

**Comment by bhowell2** [comment]
@slice-mani you need to do something like this:
```
    test_substring:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - id: tag
            run: echo "tag=$(git tag)" >> $GITHUB_OUTPUT
          - run: echo ${{ steps.tag.outputs.tag }}
          - uses: bhowell2/github-substring-action@latest
            id: first
            with:
              value: ${{ steps.tag.outputs.tag }}
              index_of_str: v
          - run: echo ${{ steps.first.outputs.substring }}
```
as there is no run command here - value is just a string. At some point I'll have to see about adding some type of `execute` param to parse instead of value.
