### ISSUE TITLE
Action does not result substring

### ISSUE THREAD

**Issue by chanyeong-jeong** [bhowell2/github-substring-action#5]
Hello,
I inserted the code below into my github workflow file. When it runs, it results in the original string rather than a substring of the initial 7 characters.

``` yaml
- uses: bhowell2/github-substring-action@v1.0.0
  id: first
  with:
    value: "${{ github.sha }}"
    length_from_start: 7 # length_from_end does not give a substring either
    output_name: short_sha

- name: echo substring
  run: |
    echo ${{ steps.first.outputs.short_sha }} # expected outcome: 1a2b3c4, actual outcome: 1a2b3c4d5e....9z
```

Could you investigate why this thing happens?
